spring: 
  profiles:
    active:
    - dev
---
server:
  port: 1004
  context-path: /
spring:
  profiles: dev
  application: 
    name: microservice-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springCloud?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  application:
    name:  microservice-student
eureka:
  instance:
    hostname: localhost
    appname: microservice-student
    instance-id: microservice-student:1004
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2001.pro.com:2001/eureka/,http://eureka2002.pro.com:2002/eureka/,http://eureka2003.pro.com:2003/eureka/
info:

  groupId: $project.groupId$

  artifactId: $project.artifactId$

  version: $project.version$

  负责人: 张三

  联系电话: 110
---
server:
  port: 1004
  context-path: /
spring:
  profiles: test
  application: 
    name: microservice-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springCloud?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  application:
    name:  microservice-student
eureka:
  instance:
    hostname: localhost
    appname: microservice-student
    instance-id: microservice-student:1004
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka2001.pro.com:2001/eureka/,http://eureka2002.pro.com:2002/eureka/,http://eureka2003.pro.com:2003/eureka/
info:

  groupId: $project.groupId$

  artifactId: $project.artifactId$

  version: $project.version$

  负责人: 张三

  联系电话: 110